name: watfoe
description: "The Watfoe app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2780.0
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.252
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  flutter_link_previewer: ^3.2.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  video_player: ^2.9.1
  camera: ^0.11.0+2
  mime: ^1.0.6
  contacts_service: ^0.6.3
  flutter_libphonenumber: ^2.3.3
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OneUi
      fonts:
        - asset: assets/fonts/one-ui-6.ttf
          style: normal
        - asset: assets/fonts/one-ui-6.ttf
          weight: 500